---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - args:
          - --maxkb=2000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - id: hadolint
    repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
  - hooks:
      - additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest
        files: \.[jt]sx?$
        id: eslint
        types:
          - file
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.25.0
  - hooks:
      - id: prettier
        types_or:
          - css
          - javascript
          - jsx
          - tsx
          - ts
          - html
          - markdown
          - scss
          - yaml
          - gitignore
          - toml
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
